services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: postgres
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Recipe app 
  recipe_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_NAME=postgres
      - LLM_SERVICE_URL=http://host.docker.internal:11434
      - LLM_MODEL=mistral
      - OLLAMA_MODEL=mistral
      - REQUEST_TIMEOUT=60000
      - LLM_CONTAINERIZED=false
    ports:
      - "3000:3000"
    # volumes:
    #   # Mount everything except node_modules and use a named volume for node_modules
    #   - ./src:/app/src
    #   - ./package.json:/app/package.json
    #   - ./package-lock.json:/app/package-lock.json
    #   - ./tsconfig.json:/app/tsconfig.json
    #   - recipe_app_node_modules:/app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Liquibase for database migrations
  liquibase:
    image: liquibase/liquibase:4.31.1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/liquibase/changelog
    command: >
      --changelog-file=liquibase-changelog.xml
      --url=jdbc:postgresql://postgres:5432/postgres
      --username=postgres
      --password=yourpassword
      --search-path=/liquibase/changelog/src/db/migrations
      update

