version: '3'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Recipe app 
  recipe_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_NAME=postgres
      - LLM_SERVICE_URL=http://ollama:11434
      - OLLAMA_MODEL=tinyllama
    ports:
      - "3000:3000"
    volumes:
      # Mount everything except node_modules and use a named volume for node_modules
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - recipe_app_node_modules:/app/node_modules

  # Liquibase for database migrations
  liquibase:
    image: liquibase/liquibase:4.31.1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/liquibase/changelog
    command: >
      --changelog-file=liquibase-changelog.xml
      --url=jdbc:postgresql://postgres:5432/postgres
      --username=postgres
      --password=yourpassword
      --search-path=/liquibase/changelog/src/db/migrations
      update

  # Ollama LLM service
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    command: ["serve"]
    restart: always
    # Allocate more resources to Ollama
    deploy:
      resources:
        limits:
          cpus: '5' 
          memory: 10G
        reservations:
          cpus: '4'   
          memory: 4G 
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=5m
      # GPU environment variables (if available)
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=all

volumes:
  postgres_data:
  ollama_data:
  recipe_app_node_modules: